version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:securepassword123@db:9432/neko_search
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=securepassword123
      - POSTGRES_DB=neko_search
    ports:
      - "9432:5432"
    volumes:
      - neko_search_postgres_data:/var/lib/postgresql/data

volumes:
  neko_search_postgres_data:
